# Generated by Django 6.0.2 on 2026-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_student_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fingerprint_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
