# Generated by Django 6.0.2 on 2026-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_student_fingerprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='12345', max_length=128),
        ),
    ]
