# Generated by Django 6.0.2 on 2026-02-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0004_student_is_verified_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('guard', 'Guard'), ('visitor', 'Visitor')], default='student', max_length=20)),
                ('reference_photo', models.ImageField(upload_to='reference_photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_verified', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('degree_level', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_of_visit', models.TextField(blank=True, null=True)),
                ('cnic_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
