# Generated by Django 6.0.2 on 2026-02-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0005_entity_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='fingerprint_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
