# Generated by Django 6.0.2 on 2026-03-01 02:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0006_entity_fingerprint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='cnic_number',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='degree_level',
        ),
        migrations.AlterField(
            model_name='entity',
            name='fingerprint_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='verifier.entity')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
