# Generated by Django 6.0.2 on 2026-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0007_remove_entity_cnic_number_remove_entity_degree_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='driver_cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='number_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='owner_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='ownership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='vehicle_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('guard', 'Guard'), ('visitor', 'Visitor'), ('vehicle', 'Vehicle')], default='student', max_length=20),
        ),
    ]
