# Generated by Django 6.0.2 on 2026-03-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0008_entity_driver_cnic_entity_driver_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='reference_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
