# Generated by Django 4.2.29 on 2026-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0009_entity_reference_details_entity_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
