# Generated by Django 4.2.29 on 2026-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0010_alter_attendancelog_id_alter_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='number_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='reference_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
