# Generated by Django 4.2.29 on 2026-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0011_attendancelog_exit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
